# Generated by Django 5.0.4 on 2024-04-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle_estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Itens',
        ),
    ]
